//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiResort
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int Id { get; set; }
        public int WorkersPositionId { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Passwords { get; set; }
        public Nullable<System.DateTime> LastEntrance { get; set; }
        public bool IsSucces { get; set; }

        public string IsSuccessString()
        {
            string result = IsSucces ? "Да" : "Нет";
            return result;
        }

        public virtual WorkersPositions WorkersPositions { get; set; }
    }
}
