//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkiResort
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Services = new HashSet<Services>();
        }
    
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public int ClientCode { get; set; }
        public int OrderStatus { get; set; }
        public string CloseDate { get; set; }
        public Nullable<int> RentalTime { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual OrdersStatutes OrdersStatutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
    }
}
